[package]
name = "exploration_example"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.33.0"
sembas = { git = "https://github.com/Thomj-Dev/SEMBAS.git", features = [
    "global_search",
    "surfacing",
] }
