[package]
name = "uas"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.33.0"
sembas = { git = "https://github.com/Thomj-Dev/SEMBAS.git", features = [
    "api",
    "sps",
], branch = "revision-v0.3.0-rc_serialization" }
bytemuck = "1.18.0"
