[package]
name = "uas"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.33.0"
sembas = { git = "https://github.com/Thomj-Dev/SEMBAS.git", features = ["api"] }
serde = "1.0.204"
serde_json = "1.0.120"
